### ISSUE TITLE
step 25 in lab 4 ReadMe needs update

### ISSUE THREAD

**Issue by sridhar1982** [kennyk65/Microservices-With-Spring-Student-Files#1]
Currently step 25 does NOT instruct to add the cloud-config-client dependency in pom.xml. without this, client applications does not communicate with config server. The following lines should be added to each of client application's pom.xml

     ```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-client</artifactId>
        </dependency>
    ```

Thank you for the excellent course in Udemy. Really enjoying it and doing all the labs.

**Comment by kennyk65** [comment]
Hi Sridar,  Thanks for your time looking into this.  

You are correct - to incorporate the use of the config server, the clients must add the spring-cloud-config-client.  I had intended the bonuses to be less structured, but I can see here that I've spelled out the other steps in detail, so omitting this step wouldn't make sense.  I'll make the change.  thanks.

**Comment by kennyk65** [comment]
Fixed.  On behalf of future students, thanks for pointing out this issue.
