### ISSUE TITLE
Lab 3 - Could not resolve placeholder 'lucky-word' in string value "${lucky-word}"

### ISSUE THREAD

**Issue by timlee** [kennyk65/Microservices-With-Spring-Student-Files#22]
I used all the server and client source files provided in Lab 3 or type all the sources from the video.
Having an issue trying to get the client to run. (Server starts fine).

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'luckyWordController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String com.example.LuckyWordController.luckyWord; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'lucky-word' in string value "${lucky-word}"
[lab-3-client.zip](https://github.com/kennyk65/Microservices-With-Spring-Student-Files/files/2575311/lab-3-client.zip)

**Comment by ddavid96** [comment]
I'm having the same problem. Did you manage to solve this?
