### ISSUE TITLE
Lab 3 - Could not resolve placeholder 'lucky-word' in string value "${lucky-word}"

### ISSUE THREAD

**Issue by ddevice1234** [kennyk65/Microservices-With-Spring-Student-Files#6]
Having an issue trying to get the client to run. (Server starts fine).

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'luckyWordController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String com.example.LuckyWordController.luckyWord; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'lucky-word' in string value "${lucky-word}"

[lab-3-client.zip](https://github.com/kennyk65/Microservices-With-Spring-Student-Files/files/377625/lab-3-client.zip)

**Comment by ddevice1234** [comment]
Nevermind. My lab-3-client.yml file was not formatted correctly. (I didn't have a space after the colon). I just learned that yml filesare very particular about their spacing. :-(

**Comment by aflaifel** [comment]
i have the same issue but couldn't fix it yet

**Comment by MShodmonov** [comment]
Me too
